# Generated by Django 4.2.29 on 2026-05-07 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='Umumiy ball')),
                ('tests_completed', models.PositiveIntegerField(default=0)),
                ('videos_watched', models.PositiveIntegerField(default=0)),
                ('homework_done', models.PositiveIntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0, verbose_name='Ketma-ket kunlar')),
                ('last_activity', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reyting',
                'ordering': ['-total_score'],
            },
        ),
    ]
